# Generated by Django 4.2.7 on 2025-11-30 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PAS', 'Pasaporte'), ('NIT', 'NIT')], max_length=10)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('delivered', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='back_user_name_1d0fb8_idx'), models.Index(fields=['email'], name='back_user_email_a222e3_idx'), models.Index(fields=['active'], name='back_user_active_147908_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('TEQUILA', 'Tequila'), ('CERVEZA', 'Cerveza'), ('VINO', 'Vino'), ('WHISKEY', 'Whiskey'), ('AGUARDIENTE', 'Aguardiente'), ('RON', 'Ron'), ('COCTEL', 'Coctel'), ('VODKA', 'Vodka')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('TEQUILA', 'Tequila'), ('CERVEZA', 'Cerveza'), ('VINO', 'Vino'), ('WHISKEY', 'Whiskey'), ('AGUARDIENTE', 'Aguardiente'), ('RON', 'Ron'), ('COCTEL', 'Coctel'), ('VODKA', 'Vodka')], db_index=True, max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='back_produc_name_f4f244_idx'), models.Index(fields=['price'], name='back_produc_price_5cb1eb_idx'), models.Index(fields=['product_type'], name='back_produc_product_906077_idx'), models.Index(fields=['active'], name='back_produc_active_ea7b65_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(db_index=True, default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='back.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='back.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['delivered'], name='back_custom_deliver_1544cd_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='back_custom_name_098327_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer'], name='back_paymen_custome_e8adef_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['product'], name='back_paymen_product_858e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='back_paymen_payment_5d0eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid'], name='back_paymen_paid_75f6a4_idx'),
        ),
    ]
