# Generated by Django 4.2.7 on 2025-11-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CERVEZAS', 'CERVEZAS'), ('CIGARILLOS', 'CIGARILLOS'), ('GOLOSINAS', 'GOLOSIONAS'), ('LICORES', 'LICORES')], db_index=True, max_length=20),
        ),
    ]
