# Generated by Django 4.2.7 on 2025-12-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_product_size_alter_product_category'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='back_produc_product_906077_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='back_produc_categor_bacecc_idx'),
        ),
    ]
