# Generated by Django 4.2.7 on 2025-12-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_remove_product_back_produc_product_906077_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='otros',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CERVEZAS', 'CERVEZAS'), ('CIGARILLOS', 'CIGARILLOS'), ('GOLOSINAS', 'GOLOSIONAS'), ('LICORES', 'LICORES'), ('OTROS', 'OTROS')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['otros'], name='back_produc_otros_987db3_idx'),
        ),
    ]
