# Generated by Django 4.2.7 on 2025-12-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_product_otros_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
