# Generated by Django 4.2.7 on 2026-01-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_product_imagen'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'category'], name='back_produc_active_7fa274_idx'),
        ),
    ]
